charts/em-hrs/Chart.yaml, charts/em-hrs/values.yaml, infrastructure/main.tf, infrastructure/variables.tf, src/main/resources/bootstrap.yaml
=> Added in db module

infrastructure/main.tf
Added in storage account secrets
=> Added in storage account secrets

Makefile, build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/AuditActions.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/AuditEntry.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/RootControllerTest.java
https://tools.hmcts.net/jira/browse/EM-3346
Initial Project Build - Adding Auditing Code
```
[ ] Yes
[ x] No
```
=> Em 3346 import auditing code and models from dm

.gitignore, build-code-checks.gradle, build-dependencies.gradle, build-dependency-management.gradle, build-liquibase.gradle, build-plugins.gradle, build-source-sets.gradle, build-tasks.gradle, build.gradle, src/aat/java/uk/gov/hmcts/reform/em/hrs/smoke/SmokeTest.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/testutil/TestUtil.java, src/aat/resources/application.yml, src/aat/resources/conf/logback.xml
https://tools.hmcts.net/jira/browse/EM-3424
Addition of smoke test to progress build in AAT environment. Refactored gradle dependencies to assist with using other projects as references
```
[ ] Yes
[x ] No
```
=> Added Smoke Test and refactored gradle build

build-dependencies.gradle, charts/em-hrs/Chart.yaml, charts/em-hrs/values.yaml, infrastructure/main.tf, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3454
=> Added in S2S details

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml
https://tools.hmcts.net/jira/browse/EM-3534
Updated the image name
```
[ ] Yes
[X] No
```
=> Updated the image name

build.gradle
downgrade ben manes library as experiment to fix builds
```
[ ] Yes
[ x] No
```
=> downgrade ben manes library

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/FolderRepositoryTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingShareesRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingShareesService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingShareesServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareService.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingSegmentServiceImplTests.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/HearingRecordingShareesServiceImplTests.java
https://tools.hmcts.net/jira/browse/EM-3413
Created the service and repository layers for HearingRecordingSharees and HearingRecordingSegment
```
[ ] Yes
[X] No
```
=> EM-3413 Create Service and Repository Layers 

build.gradle, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, config/checkstyle/checkstyle.xml, docker-compose-dependencies.yml, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/GetRootUrlTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/JwtGrantedAuthoritiesConverter.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/BaseTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/TestSecurityConfiguration.java
https://tools.hmcts.net/jira/browse/EM-3639
Added in changes for S2S auth
```
[X] Yes
[ ] No
```
=> Added in changes for S2S auth

build.gradle
N/A
Fixed CVE-2021-21295
```
[ ] Yes
[X] No
```
=> Fixed CVE-2021-21295

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3678
Fixed CVE-2020-15824, CVE-2020-29582
```
[ ] Yes
[X] No
```
=> Fixed CVE-2020-15824, CVE-2020-29582

Jenkinsfile_CNP, Jenkinsfile_nightly, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java
=> add s2s secrets to jenkins files

docker/dependencies/idam-create-hrs-system-user.sh, docker/dependencies/start-local-environment.sh, src/main/resources/application.yaml
=> fix system user docker setup

src/main/resources/db/db.changelog-master.xml
fix db changelog
```
[ ] Yes
[ ] No
```
=> fix changelog

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml
=> add storage account details

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/bootstrap.yaml
=> fix storage account details

Jenkinsfile_CNP, Jenkinsfile_nightly
=> add test url

Jenkinsfile_CNP, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/testutil/CcdAuthTokenGeneratorConfiguration.java
=> add smoke test auth-token configuration

src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
=> fix functional tests

Makefile, README.md, build.gradle, docker-compose.yml, docker/dependencies/start-local-environment.sh, docker/dependencies/stop-local-environment.sh, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/testutil/ExtendedCcdHelper.java, src/main/java/uk/gov/hmcts/reform/em/hrs/dto/HearingRecordingDto.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3711
fix up issues encountered in initial smoke test
```
[ ] Yes
[ x] No
```
=> Em 3711 run end to end integration test ready for smoke test

Jenkinsfile_nightly, audit.json, build.gradle
https://tools.hmcts.net/jira/browse/EM-3710
=> Added the Implementation of the Mutations Tests Initial Version

src/aat/java/uk/gov/hmcts/reform/em/hrs/testutil/ExtendedCcdHelper.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
https://tools.hmcts.net/jira/browse/EM-3401
Add response for when hearing recording migration request from CVP into HRS is rejected when there are too many pending requests.
```
[ ] Yes
[x] No
```
=> EM-3401 Add too many requests response

src/main/java/uk/gov/hmcts/reform/em/hrs/config/ApplicationConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AsyncConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/hrs/job/JobOrchestrator.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/IngestionQueue.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestApplicationConfig.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/job/JobOrchestratorTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/util/IngestionQueueTest.java
https://tools.hmcts.net/jira/browse/EM-3401
Externalise ingest queue and thread pool settings
```
[ ] Yes
[x] No
```
=> EM-3401 Externalise queue and thread pool settings

docker-compose-dependencies.yml, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingSceanrios.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/testutil/ExtendedCcdHelper.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/NotificationService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/NotificationServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImplTest.java
- https://tools.hmcts.net/jira/browse/EM-3405
- fixes issues in the notify service implementation
```
[ ] Yes
[X] No
```
=> fix notify client errors

Jenkinsfile_CNP, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
N/A
Updated CVP attributes
```
[ ] Yes
[X] No
```
=> Updated CVP attributes

Jenkinsfile_CNP, docker-compose-dependencies.yml, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/testutil/ExtendedCcdHelper.java, src/aat/resources/application.yml, src/main/resources/application.yaml
=> use latest image of case-data-store-api

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java
https://tools.hmcts.net/jira/browse/EM-3756
add exception handling for unique key constraints to reduce log noise
```
[ ] Yes
[ x] No
```
=> handle unique key constraint validations to reduce logging noise

Jenkinsfile_CNP, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.preview.template.yaml, docker-compose-dependencies.yml, docker/dependencies/start-local-environment.sh, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/main/resources/application.yaml
=> remove jwt and test case creation

build.gradle
N/A
Upgraded SpringBoot to 2.4.5
```
[ ] Yes
[X] No
```
=> Upgraded SpringBoot to 2.4.5

build.gradle, config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImplTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java
https://tools.hmcts.net/jira/browse/EM-3774
Add MI credentials when talking to CVP / shared services subscription 
```
[ ] Yes
[x] No
```
=> Em 3774 apply managed identity to hrs api storage client

build.gradle, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.preview.template.yaml, charts/em-hrs-api/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
N/A
Reverted SpringBoot upgrade changes
```
[ ] Yes
[X] No
```
=> Reverted SpringBoot upgrade changes

Jenkinsfile_CNP
Changed report names and removed the checkstyle aat report as we can rely on the main and test checkstyle reports
```
[ ] Yes
[ x] No
```
=> Changed report names & removed checkstyle aat report

Jenkinsfile_CNP, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/bootstrap.yaml
N/A
Added the secrets back
```
[ ] Yes
[X] No
```
=> Added the secrets back

build.gradle, charts/em-hrs-api/values.preview.template.yaml, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolver.java, src/test/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolverTest.java
https://tools.hmcts.net/jira/browse/EM-3774
Add sas token for CVP source
```
[ ] Yes
[ x] No
```
=> Em 3774 use sas token for cvp source when copying

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java
https://tools.hmcts.net/jira/browse/EM-3784
prototype of 2 x mechanisms to copy files
```
[ ] Yes
[x ] No
```
=> added experimental upload mechanisms

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/test/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolverTest.java
https://tools.hmcts.net/jira/browse/EM-3784
Use sync poller method to get past 256mb file size limit
```
[ ] Yes
[x ] No
```
=> Em 3784 prototype sync poller method

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/EM-3756
allow overrides of hrs container, as do not have access writes to perftest blob for deletion
```
[ ] Yes
[ x] No
```
=> made hrs container name injectable from vault

docker/dependencies/pull-latest-dependencies.sh, docker/dependencies/start-local-environment.sh, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImplTests.java
https://tools.hmcts.net/jira/browse/EM-3790
delete records where the CCD export has effectively failed, currently older than 24 hours
```
[ ] Yes
[x ] No
```
=> delete hearing recordings where ccdid is null, and date is older than 1 day

src/main/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJob.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/IngestionQueue.java, src/test/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobTest.java
https://tools.hmcts.net/jira/browse/EM-3799
some more fine grained exception catchers and more logging
```
[ ] Yes
[ x] No
```
=> added more logging and exception catchers

build.gradle, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
N/A
Add unit tests
```
[ ] Yes
[X] No
```
=> Add unit tests

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImplTest.java
N/A
Fix Sonar Issue
```
[ ] Yes
[X] No
```
=> Fix Sonar Issues

src/aat/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java
=> remove duplicate bearer prefix

src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecording.java, src/main/resources/db/db.changelog-master.xml
https://tools.hmcts.net/jira/browse/EM-3805
change unique constraint  from recording_ref to "folder + recording_ref"
```
[ ] Yes
[ x] No
```
=> apply unique constraint for folder and recording reg

src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-3805
check for existing files to include folder as well as recording ref
```
[ ] Yes
[x ] No
```
=> Em 3805 restrict searching for exising records by folder name

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/exception/BlobCopyException.java, src/main/java/uk/gov/hmcts/reform/em/hrs/exception/CcdUploadException.java, src/main/java/uk/gov/hmcts/reform/em/hrs/exception/DatabaseStorageException.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-3808
change from uploading to CCD whilst copying blob, to copying blob after file has copied. 
also simplify some of the future/threading
```
[ ] Yes
[x ] No
```
=> Em 3808 ccd upload job to execute after successful blob copy instead of in parallel

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java
https://tools.hmcts.net/jira/browse/EM-3809
multiple segments cause simultaneous update issues with CCD , so retry 3 times as per HLD, with a back off
```
[ ] Yes
[ x] No
```
=> add retry mechanism to ccd uploader

src/aat/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/aat/java/uk/gov/hmcts/reform/em/hrs/CaseUpdateScenarios.java
=> fix download test

build.gradle, charts/em-hrs-api/Chart.yaml, config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImplTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/exception/InvalidRangeRequestException.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClient.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/HttpHeaderProcessor.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/debug/HttpHeadersLogging.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-3819
HRS-API implement chunking mandated by frontdoor
```
[ ] Yes
[x ] No
```
=> EM-3819-HRS-API-implement-http-chunking

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml
N/A
Fixed notification key
```
[ ] Yes
[X] No
```
=> Fixed notification key

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3842
Updated em-test-helper version
```
[ ] Yes
[X] No
```
=> Updated em-test-helper version

src/main/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImpl.java
=> add extra logs when assessing permissions

config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImplTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/auditlog/AuditLogFormatter.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/AuditActions.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/AuditEntry.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingAuditEntry.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSegmentAuditEntry.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingShareeAuditEntry.java, src/main/java/uk/gov/hmcts/reform/em/hrs/model/LogOnlyAuditEntry.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesAuditEntryRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/AuditEntryService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobInfo.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClient.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/BlobstoreClientImpl.java, src/main/resources/db/db.changelog-master.xml, src/test/java/uk/gov/hmcts/reform/em/hrs/auditlog/AuditLogFormatterTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/AuditEntryServiceTests.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-3582
Implement Log formatting  as per CCD style with non db logger
added sharee auditing
general refactoring of audit service
added client Ip and ccd case id to audit logs
```
[ ] Yes
[ x] No
```
=> Em 3582 hrs create logging formater

src/main/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImplTest.java
=> pass segment to evaluator to compare to shared one

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/TestUtil.java
Adding some logic to the functional tests to ensure blobs are uploaded to the blob-store before tests are run
```
[ ] Yes
[x ] No
```
=> Working on functional tests flakiness

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java
Giving test more time to upload blob for AAT
```
[ ] Yes
[x] No
```
=> giving test more time to upload blob

Jenkinsfile_CNP, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java
changing the folder the tests are using 
```
[ ] Yes
[x] No
```
=> functional tests

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/TestUtil.java
=> adding logging

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/TestUtil.java
Adding separate loops for cvp and hrs containers
```
[ ] Yes
[ x No
```
=> updating while loop logic

build.gradle
Adding logging to the functional tests for debugging 
```
[ ] Yes
[x] No
```
=> adding logging for functional tests

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
Adding logging when posting the segment so can see the payload
```
[ ] Yes
[x] No
```
=> adding logging for post

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/config/RequestLoggingFilterConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3703
add inbound http request logging to assist with debugging, and disable sql logging by default
```
[ ] Yes
[ x] No
```
=> add request payload logging and disable sql logging by default

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java
Using emails which are in the gov notify guest list for sharing scenarios
```
[ ] Yes
[x] No
```
=> using emails in gov notify guest list

audit.json
Adding cookie to ignore list as per other APIs
```
[ ] Yes
[x] No
```
=> adding cookie to ignore list

Makefile, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/BlobstoreInspectorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/BlobStoreInspectorController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorage.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3848
add endpoint to allow comparison (and integration path) to CVP and HRS storage
```
[ ] Yes
[x ] No
```
=> add storage inspection endpoint

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3848
revert logging to info
```
[ ] Yes
[ x No
```
=> revert logging level to INFO

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/listener/CheckEndPointsApplicationReadyListener.java
https://tools.hmcts.net/jira/browse/EM-3855
add storage check to start up to help ensure connectivity available in prod 
```
[ ] Yes
[x] No
```
=> check storage on start up

src/main/java/uk/gov/hmcts/reform/em/hrs/listener/CheckEndPointsApplicationReadyListener.java
tweak to force a deploy
```
[ ] Yes
[x ] No
```
=> tweak start up messaging

security.sh
=> Revert "Update security.sh"

src/main/resources/application.yaml
n/a
reduce hibernate logging to WARN
```
[ ] Yes
[x] No
```
=> reduce hibernate logging to WARN level

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/TestUtil.java
=> keep ingested files after running f-tests

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/TestUtil.java
=> adjusting logic

build.gradle
https://tools.hmcts.net/jira/browse/EM-3969
resolve CVEs
```
[ ] Yes
[ x] No
```
=> set dependencies for tomcat and smart json

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java
https://tools.hmcts.net/jira/browse/EM-3976
make the folder search tolerant to trailing slashes to fix the stats report
```
[ ] Yes
[x ] No
```
=> Em 3976 hrs obtain stats to forecast when migration will complete

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
https://tools.hmcts.net/jira/browse/EM-3979
Clear down code wa already implemented, but was set to process > 1 day instead of > 1 hour old
```
[ ] Yes
[x] No
```
=> change stale window from 1 day to 1 hour

charts/em-hrs-api/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-3995
Updated Chart Java version
```
[ ] Yes
[X] No
```
=> Updated Chart Java version

.github/workflows/combine-prs.yml, README.md, build.gradle
n/a
add experimental workflow to combine passing PRs
```
[ ] Yes
[x ] No
```
=> Dependabot batch bump jul 29

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/DownloadHearingRecordingScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/FolderScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/HearingRecordingSegmentScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareHearingRecordingScenarios.java
https://tools.hmcts.net/jira/browse/EM-3975
Change from random to timebased casref generator to ensure uniqueness
```
[ ] Yes
[ x] No
```
=> use timebased case ref generation

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3997
Add connection pooling settings to reduce connection errors
```
[ ] Yes
[x ] No
```
=> Added hikari config with same defaults as DM store

build.gradle, config/owasp/suppressions.xml
EM-4007
fix CVE-2021-22119
```
[ ] Yes
[x] No
```
=> EM-4007: fix CVE-2021-22119

build.gradle, gradle/wrapper/gradle-wrapper.properties
upgrade gradle version
upgrade gradle version
```
[ ] Yes
[x] No
```
=> upgrade gradle version

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClientTest.java
https://tools.hmcts.net/jira/browse/EM-4017
Dump CCD upload payload to assist with debugging validation errors
```
[ ] Yes
[ x] No
```
=> Em 4017 log json payload when encountering ccd validation errors

docker-compose-dependencies.yml, docker/dependencies/start-local-environment.sh
N/A
Fix local setup
```
[ ] Yes
[X] No
```
=> Fix local setup

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/FolderRepositoryIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepositoryIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/JobInProgressRepositoryIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesRepositoryIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJob.java, src/main/java/uk/gov/hmcts/reform/em/hrs/job/JobOrchestrator.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareeServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/DefaultSnooper.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/AbstractBaseTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-4046
echDebt - Use spring annotations not JSR
```
[ ] Yes
[X] No
```
=> Em 4046 use spring annotations not JSR

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-4112
Resolve CVE-2021-22096
```
[ ] Yes
[X] No
```
=> Resolve "CVE-2021-22096"

Jenkinsfile_CNP, Jenkinsfile_nightly
n/a
fix up references to cvpsimulator container
```
[ ] Yes
[ x] No
```
=> correct env vars for nightly tests

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
none
email address change for internal test users
```
[ ] Yes
[x] No
```
=> align email address with user type

build.gradle
https://tools.hmcts.net/jira/browse/EM-4209
Updated Log4J version
```
[ ] Yes
[X] No
```
=> Updated Log4J version

config/owasp/suppressions.xml
bypass cves to unblock builds for today
https://tools.hmcts.net/jira/browse/EM-4234 - to resolve properly
=> add cves to jira to check later

src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
fix hrs container content creation removed from previous commit
=> ensure hrs container is created

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.preview.template.yaml, charts/em-hrs-api/values.yaml
move osba blob details from values.yaml to values.preview.template.yaml 
```
[ ] Yes
[x] No
```
=> move osba blob details to values.preview.template.yaml 

infrastructure/main.tf
account_replication_type ZRS
```
[ ] Yes
[x] No
```
=> account_replication_type ZRS

infrastructure/main.tf
no need ZRS for AAT storage
```
[ ] Yes
[ x No
```
=> no need ZRS for AAT storage

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-4219
Added enable_data_protection in order to enable `Soft delete`
```
[ ] Yes
[x] No
```
=> Added enable_data_protection

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-4234
```
[ ] Yes
[x] No
```
=> Set log4j version

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/bootstrap.yaml
EM-3834 add smtp secrets
```
[ ] Yes
[x] No
```
=> EM-3834 add smtp secrets

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/bootstrap.yaml
EM-3834 add recipient secret
```
[ ] Yes
[x] No
```
=> EM-3834 add recipient secret

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/BlobstoreInspectorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/BlobStoreInspectorController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/listener/CheckEndPointsApplicationReadyListener.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/StorageReport.java
EM-3834 refactor
```
[ ] Yes
[x] No
```
=> EM-3834 refactor

src/main/resources/application.yaml
EM-3834 fix smtp settings
```
[ ] Yes
[x] No
```
=> EM-3834 fix smtp settings

src/main/java/uk/gov/hmcts/reform/em/hrs/exception/EmailRecipientNotFoundException.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportServiceTest.java
Em 3834 fix smtp settings
```
[ ] Yes
[x] No
```
=> Em 3834 fix smtp settings

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-4234
```
[ ] Yes
[x] No
```
=> Fixed vulnerabilities

src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportServiceTest.java
EM-3834 make mail from configurable
```
[ ] Yes
[x] No
```
=> EM-3834 make mail from configurable

src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportService.java
EM-3834 fix mail content
```
[ ] Yes
[x] No
```
=> EM-3834 fix mail content

src/main/resources/application.yaml
add ENV var time intervals
```
[ ] Yes
[x] No
```
=> add ENV var time intervals

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/EM-4260
Increased DB config for Prod only
```
[ ] Yes
[X] No
```
=> Increased DB config for Prod only

src/main/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJob.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobTest.java
update Ccd for new files
```
[ ] Yes
[x] No
```
=> update Ccd for new files - add ENV toggle

build.gradle
try to remove logback
```
[ ] Yes
[x] No
```
=> try to remove logback

build.gradle
https://tools.hmcts.net/jira/browse/EM-4263
```
[ ] Yes
[x] No
```
=> Fix vulnerabilities

build.gradle
https://tools.hmcts.net/jira/browse/EM-4264
Fix CVE-2022-23181 , CVE-2021-42550
```
[ ] Yes
[X] No
```
=>  Resolve CVE's

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
add extra logs for in progress files
```
[ ] Yes
[x] No
```
=> add extra logs for in progress files

build.gradle
remove okhttp
```
[ ] Yes
[x] No
```
=> remove okhttp

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/repository/JobInProgressRepositoryIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/JobInProgress.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/JobInProgressRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/JobInProgressServiceImpl.java
fix JobInProgress createOn
```
[ ] Yes
[x] No
```
=> fix JobInProgress createOn

src/main/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJob.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobTest.java
reduce in progress wait time and remove unused ccd-upload property
```
[ ] Yes
[x] No
```
=> reduce in progress wait time

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
fix report count
```
[ ] Yes
[x] No
```
=> fix report count

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
https://tools.hmcts.net/jira/browse/EM-4258
Instead of masking the original exception, just throw it.
```
[ ] Yes
[X] No
```
=> Change the 500 error status for HRS API

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
filter CVP files for report count
```
[ ] Yes
[x] No
```
=> filter CVP files for report count

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/Constants.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-3706
Added in logic of 72 hrs of ttl for shared links
```
[ ] Yes
[X] No
```
=> Added in logic of 72 hrs of ttl for shared links

build.gradle
Serenity arrangements.
```
[ ] Yes
[x] No
```
=> Serenity arrangements

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java
do not delete blobs as it connects to AAT storage in master and they delete aat test blobs.
```
[ ] Yes
[ ] No
```
=> do not delete blobs

build.gradle
remove unnecessary serenity dependencies
```
[ ] Yes
[x] No
```
=> remove unnecessary serenity dependencies

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/em/hrs/service/PermissionEvaluatorImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java
remove unnecessary dependencies
```
[ ] Yes
[x] No
```
=> remove unnecessary dependencies

build.gradle
remove unnecessary plugins
```
[ ] Yes
[ ] No
```
=> remove unnecessary plugins

build.gradle, src/smokeTest/java/uk/gov/hmcts/reform/em/hrs/smoke/SmokeTest.java
remove em-test config from smoke test
```
[ ] Yes
[ ] No
```
=> remove em-test config from smoke test

src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java
https://tools.hmcts.net/jira/browse/EM-3706
Added in logs for sharee link logic
```
[ ] Yes
[X] No
```
=> Added in logs for sharee link logic

src/main/java/uk/gov/hmcts/reform/em/hrs/job/DeleteInProgressJobsTask.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/job/DeleteInProgressJobsTaskTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImplTests.java
EM-4274 add delete job
```
[ ] Yes
[x] No
```
=> EM-4274 add delete job

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/BlobUtil.java
stop delete blobs, that cause problems in AAT  user tests
```
[ ] Yes
[x] No
```
=> stop delete blobs

src/main/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImpl.java
https://tools.hmcts.net/jira/browse/EM-3706
Added in more logs for Sharee link logic
```
[ ] Yes
[X] No
```
=> Added in more logs for Sharee link logic

charts/em-hrs-api/Chart.yaml
bump java-chart
```
[ ] Yes
[x] No
```
=> bump java-chart

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreatorTest.java
bump spring boot 2.6
```
[ ] Yes
[ ] No
```
=> bump spring boot 2.6

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/bootstrap.yaml
so far it was using bulk-scan username and password for email sending. NEW HRS  username and password created and added to vault. This Pr to use new username and password for email.
```
[ ] Yes
[x] No
```
=> use HRS email user and password

build.gradle
https://tools.hmcts.net/jira/browse/EM-4126
Resolved functional tests issue
```
[ ] Yes
[X] No
```
=> Resolved functional tests issue

docker-compose-dependencies.yml, docker/postgres9-shared-dbs/Dockerfile
https://tools.hmcts.net/jira/browse/EM-4290
update postgres version to 11 for local setup
```
[ ] Yes
[X] No
```
=> update postgres version to 11 for local setup

build.gradle
remove jcenter
```
[ ] Yes
[x] No
```
=> remove jcenter

charts/em-hrs-api/Chart.yaml
bump java chart
```
[ ] Yes
[x] No
```
=> bump java chart

build.gradle
EM-4294 use HMCTS jitpack dependencies
```
[ ] Yes
[x] No
```
=> EM-4294 use HMCTS jitpack dependencies

build.gradle
N/A
Updated Sonarqube config
```
[ ] Yes
[X] No
```
=> Updated Sonarqube config

build.gradle
remove java plugin
```
[ ] Yes
[x] No
```
=> remove java plugin

build.gradle
revert gradle-build changes
```
[ ] Yes
[x] No
```
=> revert gradle-build changes

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImplTest.java
Em 4297 use jparepository to flush
```
[ ] Yes
[x] No
```
=> Em 4297 use jparepository to flush

build.gradle
use config map
```
[ ] Yes
[x] No
```
=> clean up dependency management

build.gradle
clean up dependency management-remove  commons-io
```
[ ] Yes
[x] No
```
=> clean up dependency management-remove  commons-io

infrastructure/state.tf
upgrade azurerm provider
```
[ ] Yes
[x] No
```
=> upgrade azurerm provider

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/FolderController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
https://tools.hmcts.net/jira/browse/EM-4400
Updated Swagger Doc
```
[ ] Yes
[X] No
```
=> Updated Swagger Doc

build.gradle
https://tools.hmcts.net/jira/browse/EM-4462
Fix CVE-2022-22978
```
[ ] Yes
[x] No
```
=> Fix CVE-2022-22978

src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecording.java
remove unused hearing_recording_metadata
https://tools.hmcts.net/jira/browse/EM-4578
```
[ ] Yes
[x] No
```
=> remove unused hearing_recording_metadata

build.gradle
avoid  CVE-2022-25857 caused by snakeyaml
=> added name: 'snakeyaml', version: '1.31'

src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
Add test container version so it will not run on latest.
=> Add test container version

src/main/resources/db/migration/V2__drop_hearing_recording_metadata.sql
EM-4578 drop table hearing_recording_metadata
=> EM-4578 drop table hearing_recording_metadata

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/BlobstoreInspectorTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/EmailSender.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/StorageReport.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportServiceTest.java
dd daily count to email report
https://tools.hmcts.net/jira/browse/EM-4581
```
[ ] Yes
[x] No
```
=> EM-4581 add daily count to email report

src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/EmailSender.java
=> EM-4581 send email as html

src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
use version for  test container
=> use version for  test container

build.gradle
=> depenabot upgrades

build.gradle
=> dependabot spring bumps

Dockerfile, build.gradle, config/checkstyle/checkstyle.xml, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
=> EM-4589 upgrade to java 17

src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4601 some refactoring and extra logs
=> EM-4601 some refactoring and logs

src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
add logs for FolderServiceImpl
=> add logs for FolderServiceImpl

src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-4601 Log blob storage difference

src/main/java/uk/gov/hmcts/reform/em/hrs/job/DeleteInProgressJobsTask.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/JobInProgressRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4601 fix delete job `TransactionRequiredException` error
=> EM-4601 fix delete job

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4601-change existence check log
=> EM-4601-change existence check log

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-4601 add SourceBlob exists back

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-4601 add extra log

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-4601 try catch error

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
log properties and add timeout
=> log properties and add timeout

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4601 always copy from cvp tp hrs
=> EM-4601 always copy from cvp to hrs

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4601 Skip completed file, will be reverted.
=> EM-4601 Skip completed file

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-4601 Wait for completion

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4601 revert 8948b61efa6303b1dfa20350da1d239f6fd7e091
=> EM-4601 revert 8948b61efa6303b1dfa20350da1d239f6fd7e091

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-4623 delete destination blob if it fails to complete copy
=> EM-4623 delete destination blob if it fails

build.gradle
=> EM-4634-depenabot-bumps

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/controller/BlobStoreInspectorControllerTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/JacksonMappingConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/BlobStoreInspectorController.java
Em 4626 blob inspect return json response
=> Em 4626 blob inspect

build.gradle
=> EM-4644 avoid CVE-2022-42003

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/resources/application.yaml
[EM-4666](https://tools.hmcts.net/jira/browse/EM-4666) use debug level for app-insight
=> EM-4666 use debug level for app-insight 

src/main/resources/application.yaml
EM-4666 fix logging properties
=> EM-4666 fix logging properties

build.gradle, config/owasp/suppressions.xml
[EM-4744](https://tools.hmcts.net/jira/browse/EM-4744) avoid-CVE-2022-31692
=> EM-4744 avoid-CVE-2022-31692

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/data/migration/FlywayNoOpStrategy.java
https://tools.hmcts.net/jira/browse/EM-4834
Bump flyway-core from 8.5.13 to 9.8.2
```
[ ] Yes
[X ] No
```
=> EM-4834: Bump flyway-core from 8.5.13 to 9.8.2

build.gradle
=> Revert "Bump org.flywaydb.flyway from 9.8.3 to 9.9.0"

config/owasp/suppressions.xml
[EM-4912](https://tools.hmcts.net/jira/browse/EM-4912) suppress vulnerability
latest netty jar 4.1.86 cause other vulnerabilities
=> EM-4912-suppress-vulnerability

config/owasp/suppressions.xml
[EM-4943](https://tools.hmcts.net/jira/browse/EM-4943) suppress vulnerability
=> EM-4943 suppress vulnerability

build.gradle
=> Fix CVE & Revert "Bump org.flywaydb.flyway from 9.8.3 to 9.11.0"

build.gradle, config/owasp/suppressions.xml
=> EM-5015 bump-hmcts.java

Jenkinsfile_CNP, Jenkinsfile_nightly
=> EM-5019 fix-pipeline

build.gradle
=> Revert "Bump org.flywaydb.flyway from 9.8.3 to 9.14.1"

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-5177
Updated CVE list
```
[ ] Yes
[X] No
```
=> Updated CVE list

src/main/resources/application.yaml
remove root from swagger, it causes unnecessary noise in security scan.
=> EM-5186 remove root from swagger

audit.json
EM-5186 suppress security vulnerabilities
=> EM-5186 suppress security vulnerabilities

audit.json
=> EM-5186 Update audit.json

infrastructure/main.tf
=> EM-5084 create vh container

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java, src/functionalTest/resources/application.yml, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/helper/AzureIntegrationTestOperations.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java
EM-5085 add vh connection configs
=> EM-5085 add vh connection configs

src/main/resources/db/migration/V3__add_hearing_source_column_folder.sql
EM-5087 add new column for hearing_source
we need new column to query folder names by hearing resource.
=> EM-5087 add new column for hearing_source

build.gradle
=> EM-5230 avoid CVE-2023-20862 

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml
https://tools.hmcts.net/jira/browse/EM-5258
Refer to new AppInsights details. This change will ensure logs are captured in new AppInsights.
```
[ ] Yes
[X] No
```
=> Refer to new AppInsights details

infrastructure/main.tf
=> EM-5282 fix master build

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/SecurityScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/ShareScenarios.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java
trying to simplify the existing code for spring 3 upgrade. 
this new code should equivalent of existing code"
authenticate all URLs
authorise  just  "HttpMethod.GET, "/hearing-recordings/**"
"HttpMethod.POST, "/sharees"
=> simplify security config

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.preview.template.yaml, charts/em-hrs-api/values.yaml, src/functionalTest/resources/application.yml, src/main/resources/application.yaml
=> EM-5322 rename env var

src/main/resources/application.yaml
remove debug/info  log level
```
[ ] Yes
[x] No
```
=> remove debug/info  log level

build.gradle
Fix pact error -revert pact&serenity bump
=> Fix pact error -revert pact&serenity bump

build.gradle
REMOVE 'com.github.hmcts', name: 'auth-checker-lib'
=> REMOVE 'com.github.hmcts', name: 'auth-checker-lib'

audit.json
https://tools.hmcts.net/jira/browse/EM-5398
added 1 fingerprint to audit.json
=> em-5398: added 1 fingerprint to audit.json

build.gradle, gradle/wrapper/gradle-wrapper.properties
[https://tools.hmcts.net/jira/browse/EM-5335](url)
Upgrade Gradle version to 8.1.1
```
[ ] Yes
[x] No
```
=> Upgrade Gradle Version 8

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolver.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/util/CvpConnectionResolverTest.java
[EM-5322](https://tools.hmcts.net/jira/browse/EM-5322) use vh storage connection
=> EM-5322 use vh storage connection

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/main/resources/application.yaml
add Vh counting so we can prod connection working
=> add Vh counting

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/testutil/AzureStorageContainerClientBeans.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/AzureStorageConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/FolderController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/config/TestAzureStorageConfig.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/IngestionServiceImplTest.java
Add vh hrs blob client 
```
[ ] Yes
[ ] No
```
=> EM-5322 Add vh hrs blob client

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/dto/HearingRecordingDto.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java, src/test/java/uk/gov/hmcts/reform/em/hrs/job/CcdUploadJobTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJobTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreatorTest.java
EM-5322 use enum for hearingSource
=> EM-5322 use enum for hearingSource

audit.json
https://tools.hmcts.net/jira/browse/EM-5482
added 1 fingerprint to audit.json
=> em-5482: added 1 fingerprint to audit.json

infrastructure/main.tf
create cvp simulator container
=> create cvp simulator container

src/main/resources/db/migration/V5__add_interpreter_column_hearing_recording_segment.sql
add interpreter column to hearing_recording_segment
EM-5498(https://tools.hmcts.net/jira/browse/EM-5498)
=> EM-5498 add interpreter column to hearing_recording_segment

audit.json
https://tools.hmcts.net/jira/browse/EM-5502
added 1 fingerprint to audit.json
=> em-5502: added 1 fingerprint to audit.json

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecordingSegment.java, src/main/java/uk/gov/hmcts/reform/em/hrs/dto/HearingRecordingDto.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/TestUtil.java, src/test/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingControllerTest.java
EM-5498 add interpreter to Dto
=> EM-5498 add interpreter to Dto

build.gradle
=> avoid from CVE-2023-41080

Jenkinsfile_CNP, charts/em-hrs-api/values.preview.template.yaml
=> fix preview blobstorage aSo

config/owasp/suppressions.xml
EM-5569 extend vulnerability suppress
=> EM-5569 extend vulnerability suppress

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-5527.
Removed v14 DB details. Will add in v15 DB details as separate PR as version 15 is the latest version now.
=> Removed v14 DB details

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-5527
Added v15 DB details
=> Added v15 DB details

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java
EM-5341 assert hearing resource
=> EM-5341 assert hearing resource

config/owasp/suppressions.xml
EM-5600 all versions are affected, for now suppress vulnerability
=> EM-5600 suppress vulnerability

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars
https://tools.hmcts.net/jira/browse/EM-5527
Reduced v15 DB core for non-prod env (AAT, ITHC, Demo) as the 4 core was required only for the migration of data from v11 to v15.
=> Reduced v15 DB core for non-prod env

src/main/java/uk/gov/hmcts/reform/em/hrs/service/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImpl.java
EM-5605 add logs for sharing to see what notify sends to user
=> EM-5605 add logs for sharing

build.gradle, config/owasp/suppressions.xml
EM-5616 CVE-2023-5072 vulnerability
=> EM-5616 CVE-2023-5072 vulnerability

lib/applicationinsights.json, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/FolderController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/FolderServiceImpl.java
EM-5505 reduce app-insight logs
=> EM-5505 reduce app-insight logs

src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java
EM-5401 add log for dynatrace alerting
=> EM-5401 add log for dynatrace alerting

audit.json
https://tools.hmcts.net/jira/browse/EM-5640
added fingerprints to audit.json
=> em-5640 - added fingerprints to audit.json

build.gradle
=> Revert "Update plugin org.flywaydb.flyway to v10"

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-5527
Updated force_user_permissions_trigger to update the user permissions on Prod DB after migration.
=> Updated force_user_permissions_trigger

Dockerfile
=> revert java to 17

infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/EM-5627
Removed v11 DB details on Demo.
=> Removed v11 DB details

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml
https://tools.hmcts.net/jira/browse/EM-5527
Updated v15 DB connection details.
=> Updated v15 DB connection details

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, infrastructure/main.tf
Reverts hmcts/em-hrs-api#1523
===
Had to revert the v11 DB removal changes. AS this is breaking the DB Migration step.
=> Revert "Updated v15 DB connection details"

config/owasp/suppressions.xml
EM-5679 suppress CVE-2023-36052
=> EM-5679 suppress CVE-2023-36052

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-5704 fix email counts

build.gradle
remove netty dependencymanagement
=> EM-5712  remove netty dependencymanagement

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-5704 check last 89 days as they delete the files during the days.
=> EM-5704 check last 89 days

build.gradle
EM-5717 arrange dependencymanagement
=> EM-5717 arrange dependencymanagement

build.gradle
=> Revert "Update plugin org.springframework.boot to v3.2.1"

Jenkinsfile_CNP
EM-5729 try to fix dbmigration
=> EM-5729 try to fix dbmigration

Jenkinsfile_CNP
revert https://github.com/hmcts/em-hrs-api/pull/1605
=> revert PR-1605

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-5744
resolve CVE
=> Em 5744 resolve CVE

config/owasp/suppressions.xml
[extend owasp suppressions](https://github.com/hmcts/em-hrs-api/pull/1608)
=> extend owasp suppressions

build.gradle
N/A
Updated dependant libraries.Merged 5 BOT PR's in to one.
1. https://github.com/hmcts/em-hrs-api/pull/1655/files
2. https://github.com/hmcts/em-hrs-api/pull/1654/files
3. https://github.com/hmcts/em-hrs-api/pull/1653/files
4. https://github.com/hmcts/em-hrs-api/pull/1650/files
5. https://github.com/hmcts/em-hrs-api/pull/1649/files
=> Updated dependant libraries

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
create different folder for tests for each day. It would improve traceability and response time
=> EM-5844 use different folder for tests

build.gradle, config/owasp/suppressions.xml
=> EM-5898 avoid cve

src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhBlobsTask.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-5865 delete VH recording data #1735
fix property name
=> EM-5865 delete VH recording data #1735

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-5865 delete vh blobs

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-5865 delete all vh blobs

charts/em-hrs-api/Chart.yaml
=> revert java chart

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/HearingRecordingController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/controller/WelcomeController.java, src/main/java/uk/gov/hmcts/reform/em/hrs/job/IngestionJob.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/JobInProgressServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ShareAndNotifyServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/EmailSender.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportService.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/util/EmailValidatorTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/util/HttpHeaderProcessorTest.java
https://tools.hmcts.net/jira/browse/EM-5908
fix code smells
=> fix code smells

src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTask.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTaskTest.java
EM-5865 as a test run get count of VH records before delete it.
=> EM-5865 get count of VH records

src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTask.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTaskTest.java
=> EM-5865 delete one record

src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTask.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTaskTest.java
EM-5865 list record ids to delete
=> EM-5865 list record ids to delete

src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTask.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTaskTest.java
EM-5865 delete all 42 VH records
=> EM-5865 delete all 42 VH records

src/main/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTask.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTaskTest.java
EM-5865 all VH records are deleted only one left as it has sharee , it can not deleting it.
with this pr it will delete sharee record and hearing record.
=> EM-5865 delete VH sharee

src/main/java/uk/gov/hmcts/reform/em/hrs/repository/ShareesAuditEntryRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTask.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/DeleteVhRecordingTaskTest.java
=> EM-5865 delete audit data

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
add log to see 4 VH file names, get idea how they look.
=> add log to see 4 VH file names

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/storage/DefaultHearingRecordingStorageIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorage.java, src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportServiceTest.java
=> EM-5964 refactor report

charts/em-hrs-api/values.preview.template.yaml
=> EM-5985 remove pr db auth

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.preview.template.yaml, charts/em-hrs-api/values.yaml
EM-5985 remove user/password for db
=> EM-5985 remove user/password for db

charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml
https://tools.hmcts.net/jira/browse/EM-5989.
Disabled Spot instances.
=> Disabled Spot instances

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/EM-5991
Extended the suppression date
=> Extended the suppression date

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> log vh-hrs file difference

src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/AbstractBaseTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/AuditEntryServiceTests.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClientTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/SummaryReportServiceTest.java
=> EM-5908 fix code smells

src/test/java/uk/gov/hmcts/reform/em/hrs/service/SegmentDownloadServiceImplTest.java
=> EM-5908 fix code smells-2

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
=> EM-6040 VH report refactor

src/main/java/uk/gov/hmcts/reform/em/hrs/storage/HearingRecordingStorageImpl.java
EM-6040 Fix VH report refactor
no need to filter HRS blob storage
=> EM-6040 Fix VH report refactor

build.gradle
Reverts hmcts/em-hrs-api#1858
This is to resolve broken master build
=> Revert "Update dependency checkstyle to v10.17.0"

build.gradle
bump  'em-test-helper', version: '2.0.8'
=> bump  'em-test-helper', version: '2.0.8'

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/SecurityScenarios.java, src/functionalTest/resources/application.yml, src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java
EM-6031 validate hrs-ingestor idam token
=> EM-6031 validate hrs-ingestor idam token

Jenkinsfile_CNP
=> EM-6031 fix: add aat secrets

src/main/resources/db/migration/V6__add_index_createOn_hearing_recording_segment.sql
EM-5884 add index for hearing_recording_segment create on
=> EM-5884 add index for hearing_recording_segment create on

build.gradle, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportCsvWriter.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/MonthlyHearingReportTask.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportCsvWriterTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportServiceTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/MonthlyHearingReportTaskTest.java
=> Em-5884 add hearing reporting

build.gradle
https://tools.hmcts.net/jira/browse/EM-6083
Removing unused import, the change to use ConfigTree done as part of upgrade to spring 2.6
=> verifying in pipeline, cleaned up unused import

src/main/java/uk/gov/hmcts/reform/em/hrs/repository/HearingRecordingSegmentRepository.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportCsvWriter.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportService.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportCsvWriterTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportServiceTest.java
EM-5884 add extra fields to report
=> EM-5884 add extra fields to report

config/owasp/suppressions.xml
EM-6091 suppress vulnerabilities
=> EM-6091 suppress vulnerabilities

src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailService.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceTest.java
=> EM-5884 fix email tittle

src/test/java/uk/gov/hmcts/reform/em/hrs/componenttests/AbstractDataSourceTest.java
=> EM-6107 - fix container registry

src/functionalTest/resources/application.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-6121
use dummy default key
=> use dummy default key

charts/em-hrs-api/values.preview.template.yaml, src/main/resources/application.yaml
=> make dummy value more dummy

build.gradle, charts/em-hrs-api/Chart.yaml, charts/em-hrs-api/values.yaml, src/cftlib/java/uk/gov/hmcts/reform/em/hrs/cftlib/CftLibConfig.java, src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/config/TTLMapperConfigTest.java, src/integrationTest/resources/ttl_jurisdiction_map.json, src/integrationTest/resources/ttl_service_map.json, src/main/java/uk/gov/hmcts/reform/em/hrs/config/TTLMapperConfig.java, src/main/java/uk/gov/hmcts/reform/em/hrs/config/TTLPropertySourceFactory.java, src/main/resources/application.yaml, src/main/resources/ttl_jurisdiction_map.json, src/main/resources/ttl_service_map.json
https://tools.hmcts.net/jira/browse/EM-6020
create static look-up table
=> create static look-up table

charts/em-hrs-api/values.aat.template.yaml, charts/em-hrs-api/values.preview.template.yaml
EM-6127 use test notify api-key
use pretend to send api key for functional test in Preview and aat-staging,
use real api-key for AAT.
=> EM-6127 use test notify api-key

src/integrationTest/java/uk/gov/hmcts/reform/em/hrs/service/email/MonthlyHearingReportTaskTest.java, src/integrationTest/resources/application-test.yaml, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/DateListConverter.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/MonthlyHearingReportTask.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/DateListConverterTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/MonthlyHearingReportTaskTest.java
EM-5884 make report date configurable
=> EM-5884 make report date configurable

build.gradle, config/owasp/suppressions.xml
arrange owasp suppressions
See [EM-6203](https://tools.hmcts.net/jira/browse/EM-6203)
=> EM-6203 extend owasp suppression

Jenkinsfile_nightly
=> EM-6254 fix nightly build

README.md, src/main/java/uk/gov/hmcts/reform/em/hrs/domain/HearingRecording.java, src/main/resources/db/migration/V8__drop_column_ttl_hearing_recording.sql
###Jira link
[EM-6034](https://tools.hmcts.net/jira/browse/EM-6034) drop ttl column to change its type from timestamp to date
previous pr stuck https://github.com/hmcts/em-hrs-api/pull/2070
=> Em-6034 drop ttl

src/main/java/uk/gov/hmcts/reform/em/hrs/config/security/SecurityConfiguration.java
enable to access swagger ui , currently it gets 401 error
=> enable to access swagger ui 

src/main/java/uk/gov/hmcts/reform/em/hrs/controller/BlobStoreInspectorController.java
hide endpoints to appear in swagger as they are not in use
=> hide endpoints to appear in swagger

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java
https://tools.hmcts.net/jira/browse/EM-6291 nigtly build was failing because of race condition in case creation.
=> EM-6291 fix failing functional test

Jenkinsfile_CNP, Jenkinsfile_nightly, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java, src/functionalTest/resources/application.yml
[EM-6034](https://tools.hmcts.net/jira/browse/EM-6034) fix staging pipeline
- as ttl is not enabled in AAT we need to configure functional test
=> EM-6034 fix staging pipeline

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/FolderScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/SecurityScenarios.java
[EM-6291 ](https://tools.hmcts.net/jira/browse/EM-6199)remove sleeps and some logs to make functional test faster
=> EM-6291 remove sleeps and some logs

src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityServiceImpl.java
append bearer to service auth token if it is missing as we accept service auth without bearer in authentication
=> append bearer to service auth token if it is missing

src/main/resources/db/migration/V10__add_index_event_date_time_audit_entry.sql
[EM-6199](https://tools.hmcts.net/jira/browse/EM-6199) add index to audit table for monthly report
so we can query by date time to get audit actions to use in report
=> EM-6199 add index to audit table for monthly report

src/cftlib/java/uk/gov/hmcts/reform/em/hrs/cftlib/CftLibConfig.java, src/functionalTest/resources/application.yml
https://tools.hmcts.net/jira/browse/EM-6305
update local setup with ccd definition file
=> update local setup

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/job/UpdateJurisdictionCodesTask.java
https://tools.hmcts.net/jira/browse/EM-6336
close resource
=> close resource

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/em/hrs/consumer/IdamApiPactConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-6330
update pact to 4.6.15
=> update pact to 4.6.15

build.gradle
[EM-6345 ](https://tools.hmcts.net/jira/browse/EM-6345)remove junit4 dependencies and upgrade pitest to junit5
tested in nightly build, no problem seen
=> Em-6345 remove junit4 and bump pitest

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java
https://tools.hmcts.net/jira/browse/EM-6385
upgrade em-test-helper to 2.1.1
add retry extension
=> upgrade em-test-helper to 2.1.1

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/BaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/TtlService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImpl.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdUploadServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImplTest.java
https://tools.hmcts.net/jira/browse/EM-6395
instead of case creation time , use recording time in TTL calculation
=> EM-6395 fix TTL base time

infrastructure/state.tf
Revert "Update Terraform azurerm to ~> 4.16.0 (#2278)"
This reverts commit d8a85303bc25c989265092b50054e9c89df0a1df.
=> Revert "Update Terraform azurerm to ~> 4.16.0 (#2278)"

src/main/java/uk/gov/hmcts/reform/em/hrs/service/SecurityService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClient.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/impl/SecurityServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CcdDataStoreApiClientTest.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/SecurityServiceImplTest.java
EM-6404 refactor - remove unused methods or make private
=> EM-6404 refactor - remove methods or make private

src/main/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImpl.java
[EM-6416](https://tools.hmcts.net/jira/browse/EM-6416) add log for missing TTL config for service and jurisdiction
=> EM-6416 add log for missing TTL config for service and jurisdiction

src/main/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImpl.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/impl/TtlServiceImplTest.java
TTL config is ONLY uppercase
this chnage is making TTL lookup uppercase
=> Fix ttl service lookup

src/main/java/uk/gov/hmcts/reform/em/hrs/job/UpdateJurisdictionCodesTask.java
https://tools.hmcts.net/jira/browse/EM-6247
add log for time taken for update codes job
=> add log for time taken

src/main/resources/ttl_jurisdiction_map.json
[EM-6443](https://tools.hmcts.net/jira/browse/EM-6443) fix LU TTL time
=> EM-6443 fix LU ttl time

src/main/resources/ttl_service_map.json
https://tools.hmcts.net/jira/browse/EM-6448
add missing service id
=> add missing service id

src/cftlib/java/uk/gov/hmcts/reform/em/hrs/cftlib/CftLibConfig.java
when locally running the functional test  we need this role
=> fix - local run, add role

charts/em-hrs-api/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-6547
Upgrading to oci charts, bumping minor chart version
bumped java chart version
bumped blobstore chart version
=> EM-6547 Upgrading oci charts

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceConfig.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceTest.java
[EM-6445](https://tools.hmcts.net/jira/browse/EM-6445) change weekly attachment name
=> EM-6445 change weekly attachment name

src/functionalTest/java/uk/gov/hmcts/reform/em/hrs/IngestScenarios.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreator.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/ccd/CaseDataContentCreatorTest.java
https://tools.hmcts.net/jira/browse/EM-6598
Updated OverrideTTL to set as null.
Unit test and functional test updated. QA activity will be completed on Demo to ensure the caseData has the correct value of null set for OverrideTTL.
=> Updated OverrideTTL to set as null

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EM-6549 disable public access for DEMO
=> EM-6549 disable public access,private end point

build.gradle, src/main/java/uk/gov/hmcts/reform/em/hrs/job/DeleteOrphanHearingRecordingAatTask.java
https://tools.hmcts.net/jira/browse/EM-6357
Added in DeleteOrphanHearingRecordingAatTask to delete the orphan HRS metadata from HRS DB on AAT ONLY. This will be one time activity.
N/A
=> Added in DeleteOrphanHearingRecordingAatTask

src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailService.java, src/main/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceConfig.java, src/test/java/uk/gov/hmcts/reform/em/hrs/service/email/HearingReportEmailServiceConfigTest.java
[EM-6601 ](https://tools.hmcts.net/jira/browse/EM-6601)change weekly report email body
=> EM-6601 change weekly report email body

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/EM-6549
for private endpoint tests disable demo syncronization
=> for private endpoint tests disable demo syncronization

Jenkinsfile_CNP
pr merged to create private end point so we are. enabling demo synchronisation again
https://tools.hmcts.net/jira/browse/EM-6549
=> enable demo synronization

src/main/resources/db/migration/V12__add_indexes.sql
=> Revert "Added Indexes"

infrastructure/prod.tfvars
See [VIH-11462](https://tools.hmcts.net/jira/browse/VIH-11462)
Create private endpoint for prod hrs storage in cvp prod vnet to enable private connectivity between storage
This has been done in lower environments already
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> VIH-11462 create private endpoint for prod hrs storage in cvp
